from __future__ import annotations

from .shared import *  # noqa: F401,F403

def apply_shared_settings(
    shared: dict[str, bool | int | float | str],
    *,
    project: ResolvedProjectConfig | None = None,
    shared_config_path: Path | None = None,
) -> None:
    global SHARED
    global ACTIVE_PROJECT
    global CURRENT_CONFIG_PATH
    global SYMBOL
    global SEQ_LEN
    global TARGET_HORIZON
    global FEATURE_ATR_PERIOD
    global FEATURE_ATR_RATIO_PERIOD
    global FEATURE_BOLLINGER_PERIOD
    global FEATURE_DONCHIAN_FAST_PERIOD
    global FEATURE_DONCHIAN_SLOW_PERIOD
    global FEATURE_RET_2_PERIOD
    global FEATURE_RET_3_PERIOD
    global FEATURE_RET_6_PERIOD
    global FEATURE_RET_12_PERIOD
    global FEATURE_RET_20_PERIOD
    global FEATURE_RSI_FAST_PERIOD
    global FEATURE_RSI_SLOW_PERIOD
    global FEATURE_RV_LONG_PERIOD
    global FEATURE_SMA_FAST_PERIOD
    global FEATURE_SMA_MID_PERIOD
    global FEATURE_SMA_SLOW_PERIOD
    global FEATURE_SMA_SLOPE_SHIFT
    global FEATURE_SMA_TREND_FAST_PERIOD
    global FEATURE_SPREAD_Z_PERIOD
    global FEATURE_STOCH_PERIOD
    global FEATURE_STOCH_SMOOTH_PERIOD
    global FEATURE_TICK_COUNT_PERIOD
    global FEATURE_TICK_IMBALANCE_FAST_PERIOD
    global FEATURE_TICK_IMBALANCE_SLOW_PERIOD
    global TARGET_ATR_PERIOD
    global RV_PERIOD
    global RETURN_PERIOD
    global MAX_FEATURE_LOOKBACK
    global WARMUP_BARS
    global IMBALANCE_MIN_TICKS
    global IMBALANCE_EMA_SPAN
    global USE_IMBALANCE_EMA_THRESHOLD
    global USE_IMBALANCE_MIN_TICKS_DIV3_THRESHOLD
    global PRIMARY_BAR_SECONDS
    global PRIMARY_TICK_DENSITY
    global BAR_DURATION_MS
    global DEFAULT_FIXED_MOVE
    global LABEL_SL_MULTIPLIER
    global LABEL_TP_MULTIPLIER
    global EXECUTION_SL_MULTIPLIER
    global EXECUTION_TP_MULTIPLIER
    global USE_ALL_WINDOWS
    global DEFAULT_EPOCHS
    global DEFAULT_BATCH_SIZE
    global DEFAULT_MAX_TRAIN_WINDOWS
    global DEFAULT_MAX_EVAL_WINDOWS
    global DEFAULT_PATIENCE
    global DEFAULT_LOSS_MODE

    SHARED = dict(shared)
    ACTIVE_PROJECT = project
    if shared_config_path is not None:
        CURRENT_CONFIG_PATH = shared_config_path

    SYMBOL = str(SHARED.get("SYMBOL", "XAUUSD")).strip() or "XAUUSD"
    SEQ_LEN = int(SHARED["SEQ_LEN"])
    TARGET_HORIZON = int(SHARED["TARGET_HORIZON"])
    FEATURE_ATR_PERIOD = int(SHARED["FEATURE_ATR_PERIOD"])
    FEATURE_ATR_RATIO_PERIOD = int(SHARED["FEATURE_ATR_RATIO_PERIOD"])
    FEATURE_BOLLINGER_PERIOD = int(SHARED["FEATURE_BOLLINGER_PERIOD"])
    FEATURE_DONCHIAN_FAST_PERIOD = int(SHARED["FEATURE_DONCHIAN_FAST_PERIOD"])
    FEATURE_DONCHIAN_SLOW_PERIOD = int(SHARED["FEATURE_DONCHIAN_SLOW_PERIOD"])
    FEATURE_RET_2_PERIOD = int(SHARED["FEATURE_RET_2_PERIOD"])
    FEATURE_RET_3_PERIOD = int(SHARED["FEATURE_RET_3_PERIOD"])
    FEATURE_RET_6_PERIOD = int(SHARED["FEATURE_RET_6_PERIOD"])
    FEATURE_RET_12_PERIOD = int(SHARED["FEATURE_RET_12_PERIOD"])
    FEATURE_RET_20_PERIOD = int(SHARED["FEATURE_RET_20_PERIOD"])
    FEATURE_RSI_FAST_PERIOD = int(SHARED["FEATURE_RSI_FAST_PERIOD"])
    FEATURE_RSI_SLOW_PERIOD = int(SHARED["FEATURE_RSI_SLOW_PERIOD"])
    FEATURE_RV_LONG_PERIOD = int(SHARED["FEATURE_RV_LONG_PERIOD"])
    FEATURE_SMA_FAST_PERIOD = int(SHARED["FEATURE_SMA_FAST_PERIOD"])
    FEATURE_SMA_MID_PERIOD = int(SHARED["FEATURE_SMA_MID_PERIOD"])
    FEATURE_SMA_SLOW_PERIOD = int(SHARED["FEATURE_SMA_SLOW_PERIOD"])
    FEATURE_SMA_SLOPE_SHIFT = int(SHARED["FEATURE_SMA_SLOPE_SHIFT"])
    FEATURE_SMA_TREND_FAST_PERIOD = int(SHARED["FEATURE_SMA_TREND_FAST_PERIOD"])
    FEATURE_SPREAD_Z_PERIOD = int(SHARED["FEATURE_SPREAD_Z_PERIOD"])
    FEATURE_STOCH_PERIOD = int(SHARED["FEATURE_STOCH_PERIOD"])
    FEATURE_STOCH_SMOOTH_PERIOD = int(SHARED["FEATURE_STOCH_SMOOTH_PERIOD"])
    FEATURE_TICK_COUNT_PERIOD = int(SHARED["FEATURE_TICK_COUNT_PERIOD"])
    FEATURE_TICK_IMBALANCE_FAST_PERIOD = int(SHARED["FEATURE_TICK_IMBALANCE_FAST_PERIOD"])
    FEATURE_TICK_IMBALANCE_SLOW_PERIOD = int(SHARED["FEATURE_TICK_IMBALANCE_SLOW_PERIOD"])
    TARGET_ATR_PERIOD = int(SHARED["TARGET_ATR_PERIOD"])
    RV_PERIOD = int(SHARED["RV_PERIOD"])
    RETURN_PERIOD = int(SHARED["RETURN_PERIOD"])
    active_features = project.feature_columns if project is not None else MINIMAL_FEATURE_COLUMNS
    MAX_FEATURE_LOOKBACK = max_feature_lookback(SHARED, active_features)
    WARMUP_BARS = MAX_FEATURE_LOOKBACK
    IMBALANCE_MIN_TICKS = int(SHARED["IMBALANCE_MIN_TICKS"])
    IMBALANCE_EMA_SPAN = int(SHARED["IMBALANCE_EMA_SPAN"])
    USE_IMBALANCE_EMA_THRESHOLD = bool(SHARED["USE_IMBALANCE_EMA_THRESHOLD"])
    USE_IMBALANCE_MIN_TICKS_DIV3_THRESHOLD = bool(SHARED["USE_IMBALANCE_MIN_TICKS_DIV3_THRESHOLD"])
    PRIMARY_BAR_SECONDS = int(SHARED["PRIMARY_BAR_SECONDS"])
    PRIMARY_TICK_DENSITY = int(SHARED.get("PRIMARY_TICK_DENSITY", DEFAULT_PRIMARY_TICK_DENSITY))
    BAR_DURATION_MS = PRIMARY_BAR_SECONDS * 1000
    DEFAULT_FIXED_MOVE = float(SHARED["DEFAULT_FIXED_MOVE"])
    LABEL_SL_MULTIPLIER = float(SHARED["LABEL_SL_MULTIPLIER"])
    LABEL_TP_MULTIPLIER = float(SHARED["LABEL_TP_MULTIPLIER"])
    EXECUTION_SL_MULTIPLIER = float(SHARED["DEFAULT_SL_MULTIPLIER"])
    EXECUTION_TP_MULTIPLIER = float(SHARED["DEFAULT_TP_MULTIPLIER"])
    USE_ALL_WINDOWS = bool(int(SHARED["USE_ALL_WINDOWS"]))
    DEFAULT_EPOCHS = int(SHARED["DEFAULT_EPOCHS"])
    DEFAULT_BATCH_SIZE = int(SHARED["DEFAULT_BATCH_SIZE"])
    DEFAULT_MAX_TRAIN_WINDOWS = int(SHARED["DEFAULT_MAX_TRAIN_WINDOWS"])
    DEFAULT_MAX_EVAL_WINDOWS = int(SHARED["DEFAULT_MAX_EVAL_WINDOWS"])
    DEFAULT_PATIENCE = int(SHARED["DEFAULT_PATIENCE"])
    DEFAULT_LOSS_MODE = str(SHARED.get("DEFAULT_LOSS_MODE", "cross-entropy"))
